
export const TOPICS = [
  "Saving vs. Spending: The balance between planning for the future and enjoying the present.",
  "Debt Management: How to handle existing debt or approach new debt.",
  "Large Purchases: Disagreement over spending significant amounts (cars, vacations, furniture).",
  "Budgeting Style: Differing levels of strictness or tracking money.",
  "Financial Transparency: Keeping secrets or being dishonest about income/purchases.",
  "Investment Decisions: Risk tolerance and long-term financial strategy.",
  "Allowance/Personal Money: How much \"no-questions-asked\" spending money each partner gets.",
  "Job/Career Choices: Decisions based on salary versus passion/fulfillment.",
  "Division of Labor: Feeling the split of chores is unfair or indolent.",
  "Standards of Cleanliness: Differing ideas about what constitutes \"clean\" or \"tidy.\"",
  "Home Projects/Repairs: Prioritizing and executing maintenance.",
  "Organization Style: Messiness vs. hyper-organization.",
  "Decor and Aesthetics: Disagreements on home style (e.g., your couch debate).",
  "Quality Time: Differing definitions of what constitutes meaningful time together.",
  "Work-Life Balance: One person working too much or too little.",
  "Scheduling/Punctuality: One person being reliably late or over-scheduled.",
  "Personal Hobbies: Time spent on individual interests outside the relationship.",
  "Unrealistic Expectations: Believing the partner should naturally anticipate their needs.",
  "Screen Time: Time spent on phones, games, or social media.",
  "Decision to Have Children: Whether, when, and how many children to have.",
  "In-Laws/Extended Family: Managing time and boundaries with relatives.",
  "Family Traditions: Which traditions to keep, start, or proscribe.",
  "Sibling Relationships (of children): How to handle competition or conflict between kids.",
  "Conflict Avoidance: One or both partners absconds from difficult discussions.",
  "Tone/Delivery: Harsh language or verbal invective during arguments.",
  "Listening Skills: Feeling unheard or dismissed (a key point for you).",
  "Repair Attempts: One person refusing to engage in \"repair\" after a fight.",
  "Vulnerability: Hesitancy to open up or be emotionally honest.",
  "Passive Aggression: Expressing anger indirectly rather than openly.",
  "Frequency of Sex: Mismatched libidos or desires.",
  "Initiation of Intimacy: Who typically starts affectionate moments.",
  "Forms of Affection: Disagreement over public displays or non-sexual touch.",
  "Emotional Intimacy: The depth of sharing feelings and secrets.",
  "Political/Social Issues: Differing strong opinions on current events.",
  "Religion/Spirituality: The role of faith in your shared life.",
  "Health/Diet: Differing approaches to fitness, eating, or lifestyle.",
  "Friendships: Time spent with friends, or dislike of a partner's friend.",
  "Generosity: How much to donate or lend to friends/family.",
  "Pet Care: Responsibilities and rules regarding pets.",
  "Retirement Planning: The age or way you plan to stop working.",
  "Geographic Location: Where to live or move in the future.",
  "Handling of Change: One partner being resistant to new phases or growth.",
  "Unmet Expectations: The dubious feeling that the partner isn't living up to pre-marriage hopes.",
  "Legacy/Purpose: Differing ideas about what your shared life should stand for.",
  "Trust and Jealousy: Pervasive suspicion or monitoring.",
  "Past History: Allowing old conflicts to contaminate new ones.",
  "Respect: The general feeling of being valued or looked down upon.",
  "Personal Growth: One partner moving forward while the other remains quiescent.",
  "The \"Right\" Way to Feel: One partner denying or invalidating the other's emotions.",
];
